# Generated by Django 3.1.3 on 2021-11-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='student_id',
            new_name='customer_id',
        ),
        migrations.AlterField(
            model_name='order',
            name='product_id',
            field=models.ManyToManyField(to='hostel.Product'),
        ),
    ]
